repos:
  - repo: local
    hooks:
      - id: swift-test
        name: Swift Tests  
        entry: bash -c 'timeout 120s swift test --parallel || echo "Tests skipped (timeout or failed)"'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint --fix --quiet
        language: system
        files: \.swift$
        stages: [pre-commit]
        
      - id: architecture-check
        name: Architecture Check
        entry: |
          bash -c 'if [[ "$(uname -m)" != "arm64" ]]; then echo "Error: This project requires Apple Silicon (arm64)"; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        
      - id: performance-check
        name: Performance Regression Check
        entry: bash -c 'timeout 60s swift test --filter testPerformanceRegression || echo "Performance check skipped (timeout or failed)"'
        language: system
        pass_filenames: false
        stages: [pre-commit]
        
      - id: memory-check
        name: Memory Leak Check
        entry: leaks --atExit -- swift test
        language: system
        pass_filenames: false
        stages: [pre-push]
        
      - id: no-homebrew-name
        name: No Homebrew Name Check
        entry: |
          bash -c 'if grep -r "Homebrew" Sources/ Tests/ --include="*.swift" | grep -v "// Attribution" | grep -v "homebrew-core" | grep -v "Homebrew bottle" | grep -v "Homebrew on Apple" | grep -v "Homebrew tap" | grep -v "Homebrew placeholder" | grep -v "homebrew/" | grep -v "/opt/homebrew" | grep -v "Homebrew compatibility" | grep -v "IsHomebrew"; then echo "Error: Found inappropriate Homebrew reference in code. Use Velo instead."; exit 1; fi'
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]